# Generated by Django 4.1.3 on 2023-01-02 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMarket', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='Fecha_publicacion',
        ),
        migrations.AddField(
            model_name='categoria',
            name='Anio_publicacoin',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
